package com.defense.composetestapp.di

const val DI_NAMED_BASE_URL = "DI_NAMED_BASE_URL"
const val DI_NAMED_BASE_RETROFIT = "DI_NAMED_BASE_RETROFIT"

const val DI_NAMED_UNSPLASH_BASE_URL = "DI_NAMED_UNSPLASH_BASE_URL"
const val DI_NAMED_UNSPLASH_BASE_RETROFIT = "DI_NAMED_UNSPLASH_BASE_RETROFIT"
